name: Make fasta file
on: [push]
jobs:
  make_fasta:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Concatinate consensus sequences
        run: cat consensus_sequences/*.fasta | gzip -9 > consensus_sequences.fasta.gz
      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::SequenceUpload_$(date +"%Y.%m.%d_%H-%M")"
      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: consensus_sequences.fasta.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
